language: java
sudo: required
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - mvn --batch-mode release:update-versions -DdevelopmentVersion=${TRAVIS_TAG}
script:
 - mvn clean install
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/travis-ci-tutorial-java-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    tags: true
