language: java
jdk:
 - oraclejdk8
script:
 - mvn clean install
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/travis-ci-tutorial-java-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
