language: java
jdk:
 - oraclejdk8
script:
 - mvn clean install
deploy:
  provider: releases
  api_key: b777b89be7348537b7adb804fda0e4b3184def4b
  file: target/travis-ci-tutorial-java-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
