language: java
jdk:
 - oraclejdk8
script:
 - mvn clean install
deploy:
  provider: releases
  branch: master
  skip_cleanup: true
  user: benisavu@gmail.com
  password: B@nanana1
  file: target/travis-ci-tutorial-java-0.0.1-SNAPSHOT.jar
  on:
    tags: true
